apiVersion: v1
kind: ConfigMap
metadata:
  name: nrp-accounting-config
data:
  PROMETHEUS_URL: "https://thanos.nrp-nautilus.io"
  PORTAL_RPC_URL: "https://portal.nrp.ai/rpc"
  CLICKHOUSE_DATABASE: "access_accounting"
  CLICKHOUSE_PORT: "8123"
  CLICKHOUSE_SECURE: "false"
  MAX_QUERY_WORKERS: "8"
  QUERY_STEP: "1h"
  RETRY_LIMIT: "4"
  PROMETHEUS_TIMEOUT_SECONDS: "300"
  PORTAL_TIMEOUT_SECONDS: "60"
  CLICKHOUSE_WRITE_BATCH_SIZE: "5000"
  INSTITUTION_CSV_URL: "https://raw.githubusercontent.com/djw8605/nrp-ror-labeler/refs/heads/main/node-institution.csv"
