apiVersion: batch/v1
kind: CronJob
metadata:
  name: nrp-accounting-etl
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: etl
              imagePullPolicy: Always
