apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: access-accounting

resources:
  - github.com/djw8605/nrp-clickhouse/k8s/base?ref=main
  - sealed-secret.yaml

patches:
  - path: configmap.yaml
    target:
      kind: ConfigMap
      name: nrp-accounting-config
  - path: mcp-image-pull-policy.yaml
    target:
      kind: Deployment
      name: nrp-accounting-mcp
  - path: etl-image-pull-policy.yaml
    target:
      kind: CronJob
      name: nrp-accounting-etl
  - path: mcp-ingress.yaml
    target:
      kind: Ingress
      name: nrp-accounting-mcp
  - path: namespace-delete.yaml
    target:
      kind: Namespace
  - path: patches.yaml
    target:
      kind: Secret
      name: nrp-accounting-secrets

images:
  - name: ghcr.io/djw8605/nrp-clickhouse
    newName: ghcr.io/djw8605/nrp-clickhouse
    newTag: sha-b806214
