apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nrp-accounting-secrets
  namespace: my-app-dev
spec:
  encryptedData:
    CLICKHOUSE_HOST: AgReplaceMe
    CLICKHOUSE_USER: AgReplaceMe
    CLICKHOUSE_PASSWORD: AgReplaceMe
  template:
    metadata:
      name: nrp-accounting-secrets
      namespace: my-app-dev
    type: Opaque
